### ISSUE TITLE
Header 크기

### ISSUE THREAD

**Issue by itemgiver** [Jeonghyun109/NAVER-FE-SSR#20]
Header 글씨의 크기, 검색창 길이 등이 굉장히 큰 느낌이 있습니다.
실제 네이버 서비스를 참고해서 비슷하게 맞춰야 하지 않을까 싶네요.

**Comment by JunhoMyung** [comment]
고쳐서 PR 올렸습니다

**Comment by itemgiver** [comment]
Pull request로 해결된 것 같습니다.
https://github.com/Jeonghyun109/NAVER-FE-SSR/commit/e66ffbc2a77a839d4e5f97d2795a0eed831fc41e
