### ISSUE TITLE
독립일기 키워드 mainCard 링크 에러

### ISSUE THREAD

**Issue by itemgiver** [Jeonghyun109/NAVER-FE-SSR#34]
웹툰 이미지를 누르면 다음 링크로 이동해야 하는데
json 값에 https://webtoon.naver.com/ 가 들어있어서 클릭해도 정상적인 홈페이지로 넘어가지 않는 오류가 있습니다.
모든 웹툰 이미지에 대해 동일한 오류가 발생하고 있습니다.

**Comment by Jeonghyun109** [comment]
json 데이터 수정하여 해결하였습니다!
