### ISSUE TITLE
News data 추가 (불국사, 독립일기)

### ISSUE THREAD

**Issue by itemgiver** [Jeonghyun109/NAVER-FE-SSR#36]
현재 샴고양이 키워드에 대해서만 news 섹션이 존재하는데
json 데이터를 추가해서 불국사 및 독립일기에도 news 섹션이 표시되어야할 것 같습니다.
news 데이터 추가하시고 json data 중에 order 부분도 같이 수정하시면 됩니다.

**Comment by Jeonghyun109** [comment]
독립일기나 불국사에 대해서는 따로 검색 결과에 news 섹션이 없는 것으로 알아서 news 섹션 json 데이터를 만들지 않았습니다!
여기 뉴스 탭에 들어가서 몇 개 기사 정보를 크롤링해서 넣을 순 있어요! 다만 기존 검색 결과에는 news 섹션을 찾지 못해서요, 추가해둘까요?

![image](https://user-images.githubusercontent.com/65295325/145015448-9e50bdc8-66c0-4273-9a25-b84b8d8704fd.png)

**Comment by itemgiver** [comment]
시간이 있으시다면 추가하는 것도 나쁘지 않을 것 같습니다.

**Comment by Jeonghyun109** [comment]
추가했습니다!!!
