### ISSUE TITLE
View 섹션 render 관련

### ISSUE THREAD

**Issue by JunhoMyung** [Jeonghyun109/NAVER-FE-SSR#41]
불국사 키워드만 view section 이 제대로 render 되고, 나머지 키워드는 제대로 되고 있지 않는 것 같습니다. 수정이 필요할 것 같습니다.

![image](https://user-images.githubusercontent.com/74249745/145093010-528c8600-e08e-4113-8318-32b48b6042e5.png)

![image](https://user-images.githubusercontent.com/74249745/145093045-a721d036-f3a6-46d2-af01-ea29dd2b4df7.png)

**Comment by JunhoMyung** [comment]
또한 날짜가 조금 아래에 render 되네요.

**Comment by itemgiver** [comment]
제 화면에서는 날짜가 제대로 render이 되서 다른 브라우저에서 생기는 문제는 고치기 힘들 것 같습니다.
또한 view section은 정상적으로 렌더링이 이루어지고 있습니다.
아래 독립일기 view section에 인플루언서나 tag, link가 없는 이유는 원래 포스트에 인플루언서, tag, link가 없기 때문입니다.
